[project]
name = "bi-automate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "requests>=2.32.5",
    "streamlit>=1.49.0",
    "uvicorn[standard]>=0.35.0",
]
